-- 페이지
CREATE TABLE SNS_PAGES (
	NO  INTEGER      NOT NULL, -- 넘버
	URL VARCHAR(255) NOT NULL  -- 주소
);

-- 페이지 기본키
CREATE UNIQUE INDEX PK_SNS_PAGES
	ON SNS_PAGES ( -- 페이지
		NO ASC -- 넘버
	);

-- 페이지
ALTER TABLE SNS_PAGES
	MODIFY COLUMN NO INTEGER NOT NULL AUTO_INCREMENT,
	ADD
		CONSTRAINT PK_SNS_PAGES -- 페이지 기본키
		PRIMARY KEY (
			NO -- 넘버
		);

-- 새 테이블
CREATE TABLE SNS_LOGS (
	NO    INTEGER      NOT NULL, -- 넘버
	TITLE VARCHAR(255) NOT NULL, -- 제목
	COLOR VARCHAR(255) NOT NULL, -- 색
	VALUE INTEGER      NOT NULL  -- 초
);

-- 새 테이블 기본키
CREATE UNIQUE INDEX PK_SNS_LOGS
	ON SNS_LOGS ( -- 새 테이블
		NO ASC -- 넘버
	);

-- 새 테이블
ALTER TABLE SNS_LOGS
	ADD
		CONSTRAINT PK_SNS_LOGS -- 새 테이블 기본키
		PRIMARY KEY (
			NO -- 넘버
		);

-- 새 테이블
ALTER TABLE SNS_LOGS
	ADD
		CONSTRAINT FK_SNS_PAGES_TO_SNS_LOGS -- 페이지 -> 새 테이블
		FOREIGN KEY (
			NO -- 넘버
		)
		REFERENCES SNS_PAGES ( -- 페이지
			NO -- 넘버
		);